name: Notify Discord on Push

on: 
  push:
    branches:
      - '**' # modifică aici dacă vrei pe alt branch

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            📦 Nou push pe branch-ul `${{ github.ref_name }}`
            👤 Autor: `${{ github.actor }}`
            💬 Commit: `${{ github.event.head_commit.message }}`
            🔗 [Vezi commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
